#!/usr/bin/python
#+
# Test of my ass8 PDP-8 code-generation library.
#
# Written by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys
from ass8 import \
	CodeBuffer, \
	i, \
	op, \
	dump_simh

c = CodeBuffer()
# following sequence assembles the standard RIM loader
start = 07756
c.org(start)
l1 = c.label("l1").resolve()
c.oi(i.KCC)
l2 = c.label("l2").resolve()
c.oi(i.KSF)
l2.mi(op.JMP, 0)
c.oi(i.KRB)
c.oi(i.CLL | i.RTL)
c.oi(i.RTL)
c.oi(i.SPA)
l2.mi(op.JMP, 0)
c.oi(i.RTL)
l3 = c.label("l3").resolve()
c.oi(i.KSF)
l3.mi(op.JMP, 0)
c.oi(i.KRS)
c.oi(i.SNL)
temp = c.label("temp")
temp.mi(op.DCA, 1)
temp.mi(op.DCA, 0)
l1.mi(op.JMP, 0)
temp.resolve()
c.w(0)
c.w(0)
c.done()
dump_simh(c, sys.stdout)
