#!/usr/bin/python
#+
# Test of my ass8 PDP-8 code-generation library -- generate the standard RIM loader.
#
# Written by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys
from crosscode8 import \
	CodeBuffer, \
	i, \
	op, \
	dump_simh

c = CodeBuffer()
start = 07756
c.org(start)
l1 = c.label("l1").resolve()
c.oi(i.KCC)
l2 = c.label("l2").resolve()
c.oi(i.KSF)
c.mi(op.JMP, 0, l2)
c.oi(i.KRB)
c.oi(i.CLL | i.RTL)
c.oi(i.RTL)
c.oi(i.SPA)
c.mi(op.JMP, 0, l2)
c.oi(i.RTL)
l3 = c.label("l3").resolve()
c.oi(i.KSF)
c.mi(op.JMP, 0, l3)
c.oi(i.KRS)
c.oi(i.SNL)
temp = c.label("temp")
c.mi(op.DCA, 1, temp)
c.mi(op.DCA, 0, temp)
c.mi(op.JMP, 0, l1)
c.resolve(temp)
c.w(0)
c.w(0)
c.start(start)
c.done()
dump_simh(c, sys.stdout)
