#!/usr/bin/python
#+
# Test of my ass8 PDP-8 code-generation library
#
# Written by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys
from crosscode8 import \
	CodeBuffer, \
	i, \
	op, \
	dump_simh

c = CodeBuffer()
index = c.label("index").resolve(010) # index reg
start = c.label("start")
thestr = c.label("thestr")
ptr = c.label("ptr").resolve(020) # pointer to data
c.d(ptr, thestr)
# program start
c.org(0200)
start.resolve()
c.oi(i.CLA)
c.mi(op.TAD, 0, ptr)
c.oi(i.CIA).oi(i.CMA) # AC := AC - 1
c.mi(op.DCA, 0, index)
loop = c.label("loop").resolve()
done = c.label("done")
c.oi(i.CLA)
c.mi(op.TAD, 1, index)
c.oi(i.SNA)
c.mi(op.JMP, 0, done)
c.oi(i.TLS)
out = c.label("out").resolve()
c.oi(i.TSF)
c.mi(op.JMP, 0, out)
c.mi(op.JMP, 0, loop)
done.resolve()
c.oi(i.HLT)
# data
c.org(0300)
thestr.resolve()
c.ws("THE QUICK BROWN FOX\n\0")
c.start(start)
dump_simh(c.done(), sys.stdout)
